apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: hermes-web-search-router
    files:
      - plugin.yaml=plugin/plugin.yaml
      - __init__.py=plugin/__init__.py
      - provider.py=plugin/provider.py
patches:
  - path: deployment.yaml
