apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc.yaml
configMapGenerator:
  - name: hermes-managed
    files:
      - config.yaml
  - name: hermes-environment
    literals:
      - API_SERVER_MODEL_NAME=example-hermes
